import { useState } from "react";

import {
  ArrowLeft,
  Sparkles,
  Plus,
  X,
  Save,
  RotateCcw
} from "lucide-react";

import {
  useLocation,
  useNavigate
} from "react-router-dom";

import "../styles/editProduct.css";
import { useLanguage } from "../context/LanguageContext";

function EditProduct() {

  const navigate = useNavigate();
  const location = useLocation();

  const { t } = useLanguage();

  const previousProduct =
    location.state?.product || {};

  const productImage =
    location.state?.image ||
    previousProduct.image ||
    null;

  const story =
    location.state?.story ||
    previousProduct.story ||
    "";

  const language =
    location.state?.language ||
    previousProduct.language ||
    "English";


  const [productName, setProductName] =
    useState(
      t(previousProduct.name || "Handcrafted Product")
    );


  const [description, setDescription] =
    useState(
      t(previousProduct.description || story || "")
    );


  const [category, setCategory] =
    useState(
      previousProduct.category ||
      "Handicraft"
    );


  const [material, setMaterial] =
    useState(
      t(previousProduct.material || "")
    );


  const [technique, setTechnique] =
    useState(
      t(previousProduct.technique || "")
    );


  const [color, setColor] =
    useState(
      t(previousProduct.color || "")
    );


  const [tags, setTags] =
    useState(
      (previousProduct.tags || []).map((tag) => t(tag))
    );


  const [newTag, setNewTag] =
    useState("");


  const [price, setPrice] =
    useState(
      String(
        previousProduct.price ||
        "250"
      ).replace("₹", "")
    );


  const addTag = () => {

    const tag =
      newTag.trim();

    if (
      tag &&
      !tags.includes(tag)
    ) {

      setTags([
        ...tags,
        tag
      ]);

      setNewTag("");
    }
  };


  const removeTag = (tag) => {

    setTags(
      tags.filter(
        (item) => item !== tag
      )
    );
  };


  // =====================================================
  // SAVE
  // =====================================================

  const handleSave = () => {

    const updatedProduct = {

      ...previousProduct,

      id:
        previousProduct.id ||
        Date.now(),

      name:
        productName.trim(),

      description:
        description.trim(),

      category,

      material:
        material.trim(),

      technique:
        technique.trim(),

      color:
        color.trim(),

      tags,

      price:
        `₹${price}`,

      confidence:
        previousProduct.confidence ||
        94,

      image:
        productImage,

      story,

      language
    };


    navigate(
      "/product-catalog",
      {
        state: {

          image:
            productImage,

          story,

          language,

          product:
            updatedProduct

        }
      }
    );
  };


  return (

    <div className="edit-product-page">

      {/* HEADER */}

      <header className="edit-header">

        <button
          className="edit-back-button"
          onClick={() =>
            navigate(
              "/product-catalog",
              {
                state: {
                  image: productImage,
                  product: previousProduct,
                  story,
                  language
                }
              }
            )
          }
        >

          <ArrowLeft size={16} />

          {t("Back to listing")}

        </button>


        <div className="edit-ai-label">

          <Sparkles size={14} />

          {t("AI GENERATED DETAILS")}

        </div>

        <div></div>

      </header>


      {/* INTRO */}

      <div className="edit-intro">

        <div className="edit-badge">

          <Sparkles size={12} />

          {t("REVIEW & EDIT")}

        </div>

        <h1>

          {t("Make it")} <span>{t("yours.")}</span>

        </h1>

        <p>
  {t("Review the details generated by CraftMitra AI and make any changes.")}
</p>

      </div>


      {/* MAIN */}

      <div className="edit-container">

        {/* IMAGE */}

        <div className="edit-image-section">

          <div className="edit-image-card">

            <div className="edit-image-placeholder">

              {productImage ? (

                <img
                  src={productImage}
                  alt={t(productName)}
                  className="edit-product-image"
                />

              ) : (

                <>

                  <div className="edit-craft-symbol">
                    ✦
                  </div>

                  <span>
                    {t("Product Image")}
                  </span>

                </>

              )}

            </div>


            <div className="enhanced-badge">

              <Sparkles size={12} />

              {t("AI enhanced")}

            </div>

          </div>


          <div className="ai-tip">

            <Sparkles size={15} />

            <div>

              <strong>
                {t("AI suggestion")}
              </strong>

             <p>
  {t("Product details were generated from your photo and story.")}
</p>

            </div>

          </div>

        </div>


        {/* FORM */}

        <div className="edit-form-card">

          <div className="form-heading">

            <div>

              <h2>
  {t("Product Details")}
</h2>

              <p>
                {t("Everything customers will see.")}
              </p>

            </div>

            <span className="ai-generated-pill">
              {t("AI generated")}
            </span>

          </div>


          {/* NAME */}

          <div className="form-field">

            <label>
              {t("Product Name")}
            </label>

            <input
              value={productName}
              onChange={(e) =>
                setProductName(
                  e.target.value
                )
              }
            />

          </div>


          {/* DESCRIPTION */}

          <div className="form-field">

            <label>
              {t("Description")}
            </label>

            <textarea
              value={description}
              onChange={(e) =>
                setDescription(
                  e.target.value
                )
              }
              rows="5"
            />

            <span className="character-count">

              {description.length} {t("characters")}

            </span>

          </div>


          {/* CATEGORY + MATERIAL */}

          <div className="form-row">

            <div className="form-field">

              <label>
                {t("Category")}
              </label>

              <select
                value={category}
                onChange={(e) =>
                  setCategory(
                    e.target.value
                  )
                }
              >

                <option value="Handloom">{t("Handloom")}</option>
                <option value="Handicraft">{t("Handicraft")}</option>
                <option value="Pottery">{t("Pottery")}</option>
                <option value="Jewellery">{t("Jewellery")}</option>
                <option value="Wood Craft">{t("Wood Craft")}</option>
                <option value="Other">{t("Other")}</option>

              </select>

            </div>


            <div className="form-field">

              <label>
                {t("Material")}
              </label>

              <input
                value={material}
                onChange={(e) =>
                  setMaterial(
                    e.target.value
                  )
                }
              />

            </div>

          </div>


          {/* TECHNIQUE + COLOR */}

          <div className="form-row">

            <div className="form-field">

              <label>
                {t("Craft Technique")}
              </label>

              <input
                value={technique}
                onChange={(e) =>
                  setTechnique(
                    e.target.value
                  )
                }
              />

            </div>


            <div className="form-field">

              <label>
                {t("Primary Color")}
              </label>

              <input
                value={color}
                onChange={(e) =>
                  setColor(
                    e.target.value
                  )
                }
              />

            </div>

          </div>


          {/* TAGS */}

          <div className="form-field">

            <label>
              {t("Product Tags")}
            </label>

            <div className="edit-tags">

              {tags.map((tag) => (

                <span key={tag}>

                  #{tag}

                  <button
                    type="button"
                    onClick={() =>
                      removeTag(tag)
                    }
                  >

                    <X size={11} />

                  </button>

                </span>

              ))}

            </div>


            <div className="tag-input">

              <input
                value={newTag}
                onChange={(e) =>
                  setNewTag(
                    e.target.value
                  )
                }
                onKeyDown={(e) => {

                  if (e.key === "Enter") {

                    e.preventDefault();

                    addTag();

                  }

                }}
                placeholder={t("Add a tag...")}
              />


              <button
                type="button"
                onClick={addTag}
              >

                <Plus size={14} />

              </button>

            </div>

          </div>


          {/* PRICE */}

          <div className="price-edit-section">

            <div>

              <label>
                {t("Suggested Price")}
              </label>

              <div className="price-input">

                <span>₹</span>

                <input
                  type="number"
                  value={price}
                  onChange={(e) =>
                    setPrice(
                      e.target.value
                    )
                  }
                />

              </div>

            </div>

            <div className="price-note">

              <Sparkles size={13} />

              {t("AI suggested")}

            </div>

          </div>


          {/* ACTIONS */}

          <div className="edit-actions">

            <button
              className="cancel-edit"
              onClick={() =>
                navigate(
                  "/product-catalog",
                  {
                    state: {
                      image:
                        productImage,

                      product:
                        previousProduct,

                      story,

                      language
                    }
                  }
                )
              }
            >

              <RotateCcw size={14} />

              {t("Discard")}

            </button>


            <button
              className="save-edit"
              onClick={handleSave}
            >

              <Save size={15} />

              {t("Save Changes")}

            </button>

          </div>

        </div>

      </div>

    </div>
  );
}

export default EditProduct;