import {
  ArrowLeft,
  Check,
  Edit3,
  Sparkles,
  Tag,
  Package,
  Palette,
  Layers3,
  IndianRupee,
  ShieldCheck
} from "lucide-react";

import {
  useLocation,
  useNavigate
} from "react-router-dom";

import "../styles/productCatalog.css";
import { useLanguage } from "../context/LanguageContext";

function ProductCatalog() {

  const navigate = useNavigate();
  const location = useLocation();

  const { t } = useLanguage();

  const productImage =
    location.state?.image ||
    location.state?.product?.image ||
    null;

  const product =
    location.state?.product || {

      id: Date.now(),

      name: "Handcrafted Product",

      category: "Handicraft",

      material: "Handcrafted Material",

      technique: "Traditional Craft",

      color: "Natural",

      description:
        "A handcrafted product made with care and traditional knowledge.",

      price: "₹250",

      tags: [
        "Handcrafted",
        "Traditional"
      ],

      confidence: 94,

      image: productImage

    };


  // =====================================================
  // PUBLISH
  // =====================================================

  const publishProduct = () => {

    const finalProduct = {

      ...product,

      id:
        product.id ||
        Date.now(),

      image:
        productImage ||
        product.image ||
        null,

      status:
        "Published",

      publishedAt:
        new Date().toISOString()

    };


    const existingProducts =
      JSON.parse(
        localStorage.getItem("myProducts")
      ) || [];


    // Replace existing product if editing it
    const existingIndex =
      existingProducts.findIndex(
        (item) =>
          item.id === finalProduct.id
      );


    let updatedProducts;


    if (existingIndex !== -1) {

      updatedProducts = [
        ...existingProducts
      ];

      updatedProducts[
        existingIndex
      ] = finalProduct;

    } else {

      updatedProducts = [
        finalProduct,
        ...existingProducts
      ];

    }


    localStorage.setItem(
      "myProducts",
      JSON.stringify(
        updatedProducts
      )
    );


    // Go directly to My Products
    navigate("/my-products");
  };


  return (

    <div className="catalog-page">

      <div className="catalog-header">

        <button
          className="back-button"
          onClick={() =>
            navigate("/edit-product", {
              state: {
                image: productImage,
                product
              }
            })
          }
        >

          <ArrowLeft size={16} />

          {t("Back")}

        </button>


        <div className="catalog-ai-label">

          <Sparkles size={14} />

          {t("AI GENERATED LISTING")}

        </div>

        <div className="header-spacer"></div>

      </div>


      <div className="catalog-intro">

        <div className="catalog-badge">

          <Check size={13} />

          {t("AI processing complete")}

        </div>


        <h1>

          {t("Your craft,")}

          <span>
            {t("beautifully presented.")}
          </span>

        </h1>


        <p>
  {t("We've transformed your photo and story into a marketplace-ready product listing.")}
</p>

      </div>


      <div className="catalog-container">

        {/* IMAGE */}

        <div className="product-image-card">

          <div className="image-label">
            {t("PRODUCT PHOTO")}
          </div>


          <div className="product-image-placeholder">

            {productImage ? (

              <img
                src={productImage}
                alt={t(product.name || "Handcrafted Product")}
                className="catalog-product-image"
              />

            ) : (

              <>

                <div className="craft-symbol">
                  ✦
                </div>

                <span>
                  {t("Your craft")}
                </span>

              </>

            )}

          </div>


          <div className="image-enhanced">

            <Sparkles size={13} />

            {t("AI enhanced")}

          </div>

        </div>


        {/* DETAILS */}

        <div className="product-details-card">

          <div className="generated-label">

            <Sparkles size={13} />

            {t("GENERATED BY CRAFTMITRA AI")}

          </div>


          <h2>
            {t(product.name || "Handcrafted Product")}
          </h2>


          <div className="category-line">

            <span>
              {t(product.category || "Handicraft")}
            </span>

            <span>•</span>

            <span>
              {t("Artisan Made")}
            </span>

          </div>


          <div className="description-section">

            <h3>
              {t("Description")}
            </h3>

            <p>
              {t(product.description || "A handcrafted product made with care and traditional knowledge.")}
            </p>

          </div>


          <div className="product-details-grid">

            <div className="detail-item">

              <div className="detail-icon">
                <Package size={15} />
              </div>

              <div>

                <span>
                  {t("Material")}
                </span>

                <strong>
                  {t(product.material || "Handcrafted Material")}
                </strong>

              </div>

            </div>


            <div className="detail-item">

              <div className="detail-icon">
                <Layers3 size={15} />
              </div>

              <div>

                <span>
                  {t("Technique")}
                </span>

                <strong>
                  {t(product.technique || "Traditional Craft")}
                </strong>

              </div>

            </div>


            <div className="detail-item">

              <div className="detail-icon">
                <Palette size={15} />
              </div>

              <div>

                <span>
                  {t("Color")}
                </span>

                <strong>
                  {t(product.color || "Natural")}
                </strong>

              </div>

            </div>


            <div className="detail-item">

              <div className="detail-icon">
                <Tag size={15} />
              </div>

              <div>

                <span>
                  {t("Category")}
                </span>

                <strong>
                  {t(product.category || "Handicraft")}
                </strong>

              </div>

            </div>

          </div>


          <div className="tags-section">

            <span className="section-small-title">
              {t("PRODUCT TAGS")}
            </span>


            <div className="product-tags">

              {(product.tags || []).map(
                (tag) => (

                  <span key={t(tag)}>
                    #{t(tag)}
                  </span>

                )
              )}

            </div>

          </div>


          <div className="price-section">

            <div>

              <span className="price-label">
                {t("AI SUGGESTED PRICE")}
              </span>


              <div className="price-value">

                <IndianRupee size={21} />

                {String(
                  product.price
                ).replace("₹", "")}

              </div>

            </div>


            <div className="price-confidence">

              <ShieldCheck size={16} />

              <div>

                <strong>
                  {product.confidence || 94}%
                </strong>

                <span>
                  {t("AI confidence")}
                </span>

              </div>

            </div>

          </div>


          <div className="catalog-actions">

            <button
              className="edit-product-button"
              onClick={() =>
                navigate(
                  "/edit-product",
                  {
                    state: {
                      image:
                        productImage,

                      product
                    }
                  }
                )
              }
            >

              <Edit3 size={15} />

              {t("Edit Product")}

            </button>


            <button
              className="publish-product-button"
              onClick={publishProduct}
            >

              {t("Publish Product")}

              <span>→</span>

            </button>

          </div>

        </div>

      </div>


      <div className="catalog-footer">

        <Sparkles size={15} />

        <span>
  {t("AI generated details can be edited before publishing.")}
</span>

      </div>

    </div>
  );
}

export default ProductCatalog;